name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        
    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build --if-present
      
    - name: Test
      run: npm test
      env:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

    - name: Generate Swagger Documentation
      run: |
        npm run start &
        sleep 5
        curl http://localhost:3000/swagger.json > swagger.json
